// Task 1
var num = 4
console.log(`Task 1 :${num}`);

// Task 2
let str='vikash'
console.log(`Task 2 :${str}`);

// Task 3
const bool = true
console.log(bool);

// Task 4
const number = 7
const string = 'Hello'
const boolean = false
const object = {name: 'vikash', age: 21}
const array = [1,2,3,4,5]
console.log(`Task 4 => \n Number:${number} \n String:${string}\n Boolean:${boolean}\n Object:${object.name},${object.age}\n Array:${array}`);

// Task 5
let name = 'vikash'
console.log(`Task 5 Name:${name}`);
name='VIKASH'
console.log(`Task 5 Name:${name}`);

// Task 6
const num1 = 5
// num1 = 6
console.log(num1);

// Feature Request 

function typeChecker(variable) {
    let one = variable;
    console.log(`Type of '${one}' is ${typeof one}`);
}

typeChecker('hello')